name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - class-components  # Change this to the branch you want to deploy from

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Change Folder
        run: cd react-ts-app

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: class-components  # Deploy to the gh-pages branch
          folder: build      # Deploy the "build" folder
